import loadFile from '@unctad-infovis/general-tools/helpers/LoadFile.js';
import { useEffect, useState } from 'react';

// Render-prop data loader so chart-specific shaping/props can be authored inline in Article.mdx
// (single-use per chart) while the fetch itself (assets/data/*.json, generated by
// scripts/convert_beyond_gdp_data.py) stays in one reusable place.
const ChartData = ({ children, file }) => {
  const [data, setData] = useState(null);

  useEffect(() => {
    loadFile(`assets/data/${file}`)
      .then(r => r?.json())
      .then(setData);
  }, [file]);

  if (!data) return <div className="cs_loading" />;
  return children(data);
};

export default ChartData;
