// ISO3 -> readable name, scoped to the countries actually present in the satisfaction chart
// dataset (public/assets/data/2026-beyond_gdp_satisfaction.json), per the draft's instruction
// to replace three-letter country codes with readable names in labels/tooltips.
const COUNTRY_NAMES = {
  AUS: 'Australia',
  BEL: 'Belgium',
  BLR: 'Belarus',
  CAN: 'Canada',
  CHE: 'Switzerland',
  CHL: 'Chile',
  CYP: 'Cyprus',
  DEU: 'Germany',
  DNK: 'Denmark',
  ESP: 'Spain',
  EST: 'Estonia',
  FIN: 'Finland',
  FRA: 'France',
  GMB: 'Gambia (the)',
  GRC: 'Greece',
  IRL: 'Ireland',
  ISL: 'Iceland',
  ISR: 'Israel',
  ITA: 'Italy',
  KOR: 'Korea (the Republic of)',
  LTU: 'Lithuania',
  LUX: 'Luxembourg',
  LVA: 'Latvia',
  MEX: 'Mexico',
  NLD: 'Netherlands (the)',
  NOR: 'Norway',
  NZL: 'New Zealand',
  PRT: 'Portugal',
  SVK: 'Slovakia',
  SVN: 'Slovenia',
  SWE: 'Sweden',
  TUN: 'Tunisia',
  ZAF: 'South Africa'
};

// ISO3 -> ISO2, for @unctad-infovis/unctad-flags' getFlagUrl (which expects 2-letter codes).
export const COUNTRY_ISO2 = {
  AUS: 'au',
  BEL: 'be',
  BLR: 'by',
  CAN: 'ca',
  CHE: 'ch',
  CHL: 'cl',
  CYP: 'cy',
  DEU: 'de',
  DNK: 'dk',
  ESP: 'es',
  EST: 'ee',
  FIN: 'fi',
  FRA: 'fr',
  GMB: 'gm',
  GRC: 'gr',
  IRL: 'ie',
  ISL: 'is',
  ISR: 'il',
  ITA: 'it',
  KOR: 'kr',
  LTU: 'lt',
  LUX: 'lu',
  LVA: 'lv',
  MEX: 'mx',
  NLD: 'nl',
  NOR: 'no',
  NZL: 'nz',
  PRT: 'pt',
  SVK: 'sk',
  SVN: 'si',
  SWE: 'se',
  TUN: 'tn',
  ZAF: 'za'
};

export default COUNTRY_NAMES;
