// ISO3 -> readable name, scoped to the 101 countries present in the prejudice chart dataset
// (public/assets/data/2026-beyond_gdp_prejudice.json), so the scatterplot's tooltip can show a
// full country name instead of the raw ISO3 code.
const PREJUDICE_COUNTRY_NAMES = {
  AGO: 'Angola',
  AUT: 'Austria',
  BDI: 'Burundi',
  BEL: 'Belgium',
  BEN: 'Benin',
  BFA: 'Burkina Faso',
  BGR: 'Bulgaria',
  BLR: 'Belarus',
  BLZ: 'Belize',
  BOL: 'Bolivia (Plurinational State of)',
  BWA: 'Botswana',
  CAF: 'Central African Republic (the)',
  CAN: 'Canada',
  CHE: 'Switzerland',
  CHL: 'Chile',
  CIV: "Côte d'Ivoire",
  CMR: 'Cameroon',
  COD: 'Congo (the Democratic Republic of the)',
  COL: 'Colombia',
  COM: 'Comoros (the)',
  CPV: 'Cabo Verde',
  CUB: 'Cuba',
  CYP: 'Cyprus',
  CZE: 'Czechia',
  DEU: 'Germany',
  DNK: 'Denmark',
  ESP: 'Spain',
  EST: 'Estonia',
  ETH: 'Ethiopia',
  FIN: 'Finland',
  FJI: 'Fiji',
  FRA: 'France',
  GBR: 'United Kingdom of Great Britain and Northern Ireland (the)',
  GEO: 'Georgia',
  GHA: 'Ghana',
  GIN: 'Guinea',
  GMB: 'Gambia (the)',
  GRC: 'Greece',
  GUY: 'Guyana',
  HND: 'Honduras',
  HRV: 'Croatia',
  HUN: 'Hungary',
  IRL: 'Ireland',
  ISR: 'Israel',
  ITA: 'Italy',
  KEN: 'Kenya',
  KIR: 'Kiribati',
  KOR: 'Korea (the Republic of)',
  LBR: 'Liberia',
  LSO: 'Lesotho',
  LTU: 'Lithuania',
  LUX: 'Luxembourg',
  LVA: 'Latvia',
  MAR: 'Morocco',
  MDA: 'Moldova (the Republic of)',
  MDG: 'Madagascar',
  MEX: 'Mexico',
  MLI: 'Mali',
  MLT: 'Malta',
  MMR: 'Myanmar',
  MNE: 'Montenegro',
  MNG: 'Mongolia',
  MOZ: 'Mozambique',
  MUS: 'Mauritius',
  MWI: 'Malawi',
  NAM: 'Namibia',
  NER: 'Niger (the)',
  NGA: 'Nigeria',
  NLD: 'Netherlands (the)',
  NOR: 'Norway',
  NRU: 'Nauru',
  NZL: 'New Zealand',
  PAK: 'Pakistan',
  PER: 'Peru',
  POL: 'Poland',
  PRT: 'Portugal',
  QAT: 'Qatar',
  ROU: 'Romania',
  RWA: 'Rwanda',
  SDN: 'Sudan (the)',
  SEN: 'Senegal',
  SLE: 'Sierra Leone',
  SUR: 'Suriname',
  SVK: 'Slovakia',
  SVN: 'Slovenia',
  SWE: 'Sweden',
  SWZ: 'Eswatini',
  TCD: 'Chad',
  TGO: 'Togo',
  THA: 'Thailand',
  TON: 'Tonga',
  TUN: 'Tunisia',
  TUV: 'Tuvalu',
  TZA: 'Tanzania, United Republic of',
  UGA: 'Uganda',
  VNM: 'Viet Nam',
  VUT: 'Vanuatu',
  WSM: 'Samoa',
  ZAF: 'South Africa',
  ZMB: 'Zambia',
  ZWE: 'Zimbabwe'
};

export default PREJUDICE_COUNTRY_NAMES;
